#!/usr/bin/python3

import os
import glob
import tp
import jinja2

from svgpathtools import svg2paths

artdir = 'art'
objects = {}

templateLoader = jinja2.FileSystemLoader(searchpath="./src/")
templateEnv = jinja2.Environment(loader=templateLoader, trim_blocks=True, lstrip_blocks=True)
TEMPLATE_FILE = "assets.rs.jinja2"
template = templateEnv.get_template(TEMPLATE_FILE)

def convert_path(path):
    points = []
    print (path)
    for i in path:
        points.append((i[0].real * -1.0,
                       (i[0].imag - 297.0) * -1.0))
    points.append((i[1].real * -1.0,
                  (i[1].imag - 297.0) * -1.0))
    return points

for svg_file in glob.iglob('art/*.svg'):
    paths, attributes = svg2paths(svg_file)
    obj = []
    print(svg_file)
    for i in range(len(attributes)):

        styles = attributes[i]['style'].split(';')
        styles2 = {}
        for j in styles:
            key, value = j.split(':')
            styles2[key] = value

        cur_poly = {}
        cur_poly['style'] = styles2
        cur_poly['path'] = convert_path(paths[i])
        cur_poly['tries'] = tp.earclip(cur_poly['path'])
        obj.append(cur_poly);
    objects[svg_file[4:-4]] = obj

#print(objects)

output = template.render(assets = objects)  # this is where to put args to the template renderer

with open("src/assets.rs", "w") as fh:
    fh.write(output)
#print(output)
